"""Plugin boundary contracts, registry and deterministic test doubles."""

from .contracts import (
    AdapterCapabilities,
    ChatMessage,
    Evaluator,
    ExternalBenchmarkResult,
    ExternalBenchmarkRunner,
    InferenceAdapter,
    InferenceAdapterError,
    InferenceChunk,
    InferenceErrorCode,
    InferenceRequest,
    InferenceResponse,
    MessageRole,
    PluginKind,
    ProbeResult,
    ResultExporter,
    TaskLoader,
    TelemetryCollector,
    TelemetryCollectorCapabilities,
    TokenUsage,
)
from .fakes import (
    FakeEvaluator,
    FakeExternalBenchmarkRunner,
    FakeInferenceAdapter,
    FakeResultExporter,
    FakeTaskLoader,
    FakeTelemetryCollector,
)
from .registry import DuplicatePluginError, PluginNotFoundError, PluginRegistry, PluginRegistryError

__all__ = [
    "AdapterCapabilities",
    "ChatMessage",
    "DuplicatePluginError",
    "Evaluator",
    "ExternalBenchmarkResult",
    "ExternalBenchmarkRunner",
    "FakeEvaluator",
    "FakeExternalBenchmarkRunner",
    "FakeInferenceAdapter",
    "FakeResultExporter",
    "FakeTaskLoader",
    "FakeTelemetryCollector",
    "InferenceAdapter",
    "InferenceAdapterError",
    "InferenceChunk",
    "InferenceErrorCode",
    "InferenceRequest",
    "InferenceResponse",
    "MessageRole",
    "PluginKind",
    "PluginNotFoundError",
    "PluginRegistry",
    "PluginRegistryError",
    "ProbeResult",
    "ResultExporter",
    "TaskLoader",
    "TelemetryCollector",
    "TelemetryCollectorCapabilities",
    "TokenUsage",
]
