"""Stable domain contracts for Performance Lab."""

from .compatibility import (
    ComparisonDimension as ComparisonDimension,
    CompatibilityResult as CompatibilityResult,
    NonComparabilityCode as NonComparabilityCode,
    NonComparabilityReason as NonComparabilityReason,
    compare_fingerprints as compare_fingerprints,
)
from .schemas import (  # noqa: F401
    SCHEMA_VERSION,
    AuthConfig,
    AuthStrategy,
    BenchmarkProtocol,
    Capability,
    DatasetSnapshot,
    EndpointProfile,
    ErrorInfo,
    EvaluationSuite,
    EvaluatorRef,
    ExecutionFingerprint,
    GenerationConfig,
    HardwareIdentity,
    LoadProfile,
    Measurement,
    MeasurementProvenance,
    MeasurementScope,
    ModelIdentity,
    Run,
    RunStatus,
    RuntimeIdentity,
    SampleExecution,
    SampleStatus,
    Score,
    Target,
    TaskSpec,
    TelemetryDescriptor,
    TelemetryLevel,
)
from .serialization import (
    InvalidSerializedModel as InvalidSerializedModel,
    SchemaLoadError as SchemaLoadError,
    UnsupportedSchemaVersion as UnsupportedSchemaVersion,
    load_dict as load_dict,
    load_json as load_json,
)
